version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '18080:8080'
      - '4576:4576' # SQS
      - '4579:4579' # SES
      - '4587:4587' # Events
      - '4583:4583' # SSM
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sqs,sns,events,ssm

  create_localstack_resources:
    image: anigeo/awscli
    entrypoint: '/root/localstack/create_localstack_resources.sh'
    volumes:
      - .:/root
    depends_on:
      - localstack
